const assert=require('node:assert/strict');
const {LiveFeed}=require('../sandboxes/green/prototypes/mobile-ltz/network.js');
let now=0,recoveries=0,received=0;const sources=[];
global.performance={now:()=>now};global.EventSource=class{constructor(){sources.push(this)}addEventListener(name,fn){this[name]=fn}close(){this.closed=true}};
const feed=new LiveFeed({url:'/events',receive:()=>received++,recover:()=>recoveries++});
feed.start();feed.start();assert.equal(sources.length,1);
sources[0].onerror();assert.equal(sources[0].closed,true);for(let i=0;i<100;i++)feed.tick(true);assert.equal(recoveries,1);assert.equal(sources.length,1);
now=500;feed.tick();assert.equal(sources.length,2);sources[0].onmessage({data:'{}'});assert.equal(received,0,'closed streams cannot apply queued messages');
sources[1].onmessage({data:'{}'});assert.equal(received,1);now=13000;feed.tick(true);assert.equal(sources[1].closed,true);feed.stop();now=30000;feed.tick(true);assert.equal(sources.length,2);
feed.start();assert.equal(sources.length,3);feed.stop();console.log('Single retry owner, bounded recovery, stale stream rejection and lifecycle checks passed.');
now=0;
const direct=new LiveFeed({url:'/hosted',receive:()=>{},recover:()=>recoveries++,directSource:global.EventSource});
const offer={contract:'mobile.stream',version:1,url:'https://example.test/live/events?token=fixture-only',ttl_s:600};
assert.equal(direct.offer({...offer,url:'http://example.test/live/events?token=x'}),false);
assert.equal(direct.offer({...offer,url:'https://example.test/command?token=x'}),false);
assert.equal(direct.offer(offer),true);direct.start();
let active=direct.source;active.onerror();now=500;direct.tick();direct.source.onerror();
assert.equal(direct.url,'/hosted','repeated direct errors fall back to the hosted stream');
assert.equal(direct.offer(offer),false,'do not loop between transports during cooldown');
now=62000;direct.tick();assert.equal(direct.offer(offer),true);
active=direct.source;const beforeRenew=recoveries;now=direct.directUntil-59000;direct.tick();
assert.ok(recoveries>beforeRenew,'renew before token expiry');
now=direct.directUntil+1;direct.tick();assert.equal(direct.url,'/hosted');
assert.ok(active.closed);direct.stop();
console.log('Scoped direct stream selection, renewal, cooldown, expiry and hosted fallback passed.');
