'use strict';
const assert=require('node:assert/strict');
const Viewport=require('../sandboxes/green/prototypes/mobile-ltz/viewport.js');
const v=new Viewport();v.resize(852,393);
assert.equal(v.zoom,1);assert.equal(v.cx,848);
v.setZoom(20);assert.equal(v.zoom,4);
const point=v.point(400,180);v.setZoom(3,400,180);
assert.ok(Math.abs(v.point(400,180).x-point.x)<1e-8);
assert.ok(Math.abs(v.point(400,180).y-point.y)<1e-8);
v.pan(100000,-100000);
assert.ok(v.point(0,0).x>=-1e-8);assert.ok(v.point(v.vw,v.vh).y<=960+1e-8);
v.resize(393,852);assert.equal(v.zoom,3);
v.fit();assert.equal(v.zoom,1);assert.equal(v.cx,848);assert.equal(v.cy,480);
v.setZoom(-5);assert.equal(v.zoom,1);
console.log('Viewport bounds, pinch anchor, resize and Fit passed.');
const mini=new Viewport(1696,960);mini.resize(390,580);
assert.deepEqual(mini.bounds(),{x:0,y:0,width:1696,height:960});
mini.setZoom(4);mini.center(99999,-99999);
let bounds=mini.bounds();assert.ok(bounds.x+bounds.width<=mini.w+1e-8);assert.equal(bounds.y,0);
const center=[mini.cx,mini.cy];mini.center(NaN,Infinity);assert.deepEqual([mini.cx,mini.cy],center);
mini.resize(844,390);bounds=mini.bounds();assert.ok(bounds.x>=0&&bounds.y>=0&&bounds.width<=mini.w&&bounds.height<=mini.h);
mini.fit();assert.deepEqual(mini.bounds(),{x:0,y:0,width:1696,height:960});
console.log('Minimap centering and visible bounds passed, including letterboxing.');
